### ISSUE TITLE
Issue with STAR when running crossmapper

### ISSUE THREAD

**Issue by Justin1609** [alexdobin/STAR#1313]
Hi there, 

I was advised to ask for help here regarding an error I am getting when running crossmapper on a remote host server. Crossmapper uses STAR for RNA read mapping but it seems STAR cannot create the TMP directory on the linux partition of the remote host. I have attached the error file I receive when I run crossmapper in a venv through miniconda. The command I run is the following:

`crossmapper RNA -g Yeast_A.fasta Yeast_B.fasta Yeast_C.fasta -a Yeast_A.gff Yeast_B.gff Yeast_C.gff -gn Yeast_A Yeast_B Yeast_C -r 0.01 -gb -C 360 -rlen 75,100 -rlay both -o output_folder -t 10 -max_mismatch 5 -star_tmp ~/TMP/tmps`

The output I get is then:

```
[2021-07-28 18:59:05] ERROR : See error log in /home/jasmus/Cleo_Raw_data/crossmap_out/STAR_output/STAR_mapping_stderr.txt
Traceback (most recent call last):
File "/apps/miniconda/envs/py36/bin/crossmapper", line 11, in
load_entry_point('crossmapper==1.1.1', 'console_scripts', 'crossmapper')()
File "/apps/miniconda/envs/py36/lib/python3.6/site-packages/crossmapper/crossmapper.py", line 469, in crossmapMain
parsedArgs.mapper.run()
File "/apps/miniconda/envs/py36/lib/python3.6/site-packages/crossmapper/mapper.py", line 340, in run
self.runMapping()
File "/apps/miniconda/envs/py36/lib/python3.6/site-packages/crossmapper/mapper.py", line 396, in runMapping
tmpFile = self.doMap(self.parsedArgs.simulationOutputFiles[rlen],rlen,layout)
File "/apps/miniconda/envs/py36/lib/python3.6/site-packages/crossmapper/mapper.py", line 504, in doMap
raise ExecException("STAR Execution Failed.")
crossmapper.mapper.ExecException: STAR Execution Failed.
```
Please any advice would be greatly appreciated.
[STAR_mapping_stderr.txt](https://github.com/alexdobin/STAR/files/6907386/STAR_mapping_stderr.txt)

**Comment by alexdobin** [comment]
Hi @Justin1609 

before the run, you need to make sure that TMP exists:
```
mkdir ~/TMP/
```
and remove tmps if it exists:
```
rm -rf ~/TMP/tmps/
```

Cheers
Alex

**Comment by Justin1609** [comment]
Hi Alex

I tried that, as that was what the developers of crossmapper also suggested, however that did not seem to solve the issue. Any other advice you might have?

Kind regards

Justin

**Comment by jolespin** [comment]
Does this help?

nano ~/.bash_profile

export TMPDIR=path/to/somewhere/you/can/write

**Comment by Justin1609** [comment]
Hey @jolespin 

I am trying it out now and thank you for the suggestion, I really appreciate it a lot. Will let you know if it solves the issue, otherwise I am really not sure what it could be. Also asked the server admin of the remote host for his input into what could be going wrong so will see.

**Comment by Justin1609** [comment]
Hi @jolespin and @alexdobin 

So I tried what @jolespin suggested and when I use the command "nano ~/.bash_profile" then I get the following information:

# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

So I just wanted to check should I just add "export TMPDIR=path/to/somewhere/you/can/write" underneath "export PATH" in that "~/.bash_profile" nano file? So something like this:

# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
export TMPDIR=/home/jasmus/Cleo_Raw_data

Please let me know if you think this will solve the issue, I look forward to hearing from you.

Kind regards

Justin

**Comment by Justin1609** [comment]
Hey @jolespin 

I am trying it out now and thank you for the suggestion, I really appreciate it a lot. Will let you know if it solves the issue, otherwise I am really not sure what it could be. Also asked the server admin of the remote host for his input into what could be going wrong so will see.

**Comment by Justin1609** [comment]
@alexdobin @jolespin @GrantHov 

https://github.com/Gabaldonlab/crossmapper/issues/3#issuecomment-889005746

Hi guys,

Sorry to bug you again but I am still having problems with STAR not mapping when I use crossmapper.

I have attached the relevant error information. I am running these programs on a remote host which uses a Unix OS. I have tried:

1. `mkdir ~/TMP/`
2. `-star_tmp ~/TMP/tmps` ##to allow STAR to create the non-existent tmps directory by itself, which it does do but still fails.
3. I have tried @jolespin suggestion

Please guys, I am really out of ideas as to why this is not working and really need your help with this. I am not highly skilled with programming and therefore really not sure how to go about solving this issue. Any help would really be appreciated.
[nano_bash_profile.txt](https://github.com/alexdobin/STAR/files/6938826/nano_bash_profile.txt)
[STAR error seen on terminal.txt](https://github.com/alexdobin/STAR/files/6938828/STAR.error.seen.on.terminal.txt)
[STAR_mapping_stderr.txt](https://github.com/alexdobin/STAR/files/6938830/STAR_mapping_stderr.txt)

**Comment by alexdobin** [comment]
Hi Justin,

this error is different - it cannot create FIFO files in the TMP directories.
Please confirm it by running ```mkfifo /home/jasmus/TMP/tmps/aaa```
If it fails, it means that the partition is not one of the standard *nix partitions - is it FAT or NTFS?
Then you need to point ```--outTmpDir``` to a Linux partition that supports FIFO files.

Alternatively, since you are using unzipped FASTQ files, you can omit ```--readFilesCommand cat``` from the STAR command line - then it will not use FIFO files.

Cheers
Alex
