### ISSUE TITLE
Job starsolo_count.run_starsolo:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.

### ISSUE THREAD

**Issue by ymjzhang** [alexdobin/STAR#1825]
I am running StarSolo on SeqWell-prepared scRNAseq samples. There are 26 of them, and 24 of them passed. Two samples failed after repeated trials. This is the error message on Terro.bio: 

_Failures in starsolo_workflow.starsolo_count / index 0 / attempt 1
[0:{"message":"Workflow failed"
"causedBy":[
0:{
"message":"**Job starsolo_count.run_starsolo:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.**"}]}]_

When I look into the logs, this is what I see: 

_Traceback (most recent call last):
  **File "<stdin>", line 184, in <module>
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command** '['STAR', '--genomeDir', 'genome_ref', '--runThreadN', '16', '--outFileNamePrefix', 'result/', '--soloType', 'CB_UMI_Simple', '--soloCBstart', '1', '--soloCBlen', '12', '--soloUMIstart', '13', '--soloUMIlen', '8', '--outSAMtype', 'BAM', 'SortedByCoordinate', '--outSAMattributes', 'CR', 'UR', 'CY', 'UY', 'CB', 'UB', '--readFilesCommand', 'zcat', '--readFilesIn', '220209Lov_D22-122039_0/220209Lov_D22-122039_2_sequence.fastq.gz', '220209Lov_D22-122039_0/220209Lov_D22-122039_1_sequence.fastq.gz', '--soloCBwhitelist', 'None', '--soloBarcodeReadLength', '0', '--soloFeatures', 'Gene', 'GeneFull', 'Velocyto', '--soloCellFilter', 'CellRanger2.2', '8000', '0.99', '10']' **died with <Signals.SIGSEGV: 11>.**_

I cannot think of how these two samples are different from my other 24 samples, and I do not understand the error message. Could anyone help me with troubleshooting what's going on? 
Thank you.

**Comment by alexdobin** [comment]
Hi @ymjzhang 

please post the Log.out file of the failed run.
