### ISSUE TITLE
core dump: double free or corruption (!prev)

### ISSUE THREAD

**Issue by plijnzaad** [alexdobin/STAR#360]
[Log.out.txt](https://github.com/alexdobin/STAR/files/1622682/Log.out.txt)
I keep getting `number of bytes expected from the BAM bin does not agree with the actual size on disk`  errors when running STAR 2.5.3.a as part of the STAR-fusion pipeline.
One of them also produced a core dump due to doubly free()ing a pointer, I thought you would be interested. This is on Linux CentOS7, 3.10.0-693.5.2.el7.x86_64 , glibc-2.17-196.el7.x86_64. 

The `Log.out` file is attached (as `.txt` since github doesn't want `.out`).   

The stacktrace inside `gdb` says:

```
#0  0x00000000005420bb in raise ()
#1  0x000000000054c2b5 in abort ()
#2  0x0000000000569947 in __libc_message ()
#3  0x000000000056f55a in malloc_printerr ()
#4  0x000000000057232c in _int_free ()
#5  0x000000000056355d in fclose ()
#6  0x00000000004d77ee in std::__basic_file<char>::close (this=this@entry=0x1b302e8) at basic_file.cc:278
#7  0x000000000050ef60 in std::basic_filebuf<char, std::char_traits<char> >::close (this=0x1b30280)
    at /data/gingeras/user/dobin/Software/GCC/4.7.0/objdir/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:168
#8  0x00000000004255c4 in InOutStreams::~InOutStreams() ()
#9  0x000000000045fcca in exitWithError(std::string, std::ostream&, std::ostream&, int, Parameters&) ()
#10 0x000000000047a8b9 in BAMbinSortByCoordinate(unsigned int, unsigned long long, unsigned long long, unsigned long long, std::string, Parameters*) ()
#11 0x000000000040305b in main._omp_fn.0 ()
#12 0x00000000005301c9 in gomp_thread_start (xdata=<optimized out>) at /data/gingeras/user/dobin/Software/GCC/4.7.0/gcc-4.7.0/libgomp/team.c:116
#13 0x000000000053a894 in start_thread ()
#14 0x00000000005a72e9 in clone ()

```

stderr says:
```
EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 3954   0   8


EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 7622   0   10

Jan 11 11:01:54 ...... FATAL ERROR, exiting
Jan 11 11:01:54 ...... FATAL ERROR, exiting

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 7114   0   9

Jan 11 11:01:54 ...... FATAL ERROR, exiting
*** glibc detected *** STAR: double free or corruption (!prev): 0x0000000008c40200 ***
======= Backtrace: =========
[0x56f55a]
[0x57232c]
[0x56355d]
[0x4d77ee]
[0x50ef60]
[0x4255c4]
[0x45fcca]
[0x47a8b9]
[0x40305b]
[0x5301c9]
[0x53a894]
[0x5a72e9]
======= Memory map: ========
00400000-00660000 r-xp 00000000 00:2a 6627971753                         /hpc/local/CentOS7/gen/software/STAR-2.5.3a/bin/Linux_x86_64_static/STAR
0085f000-0086f000 rw-p 0025f000 00:2a 6627971753                         /hpc/local/CentOS7/gen/software/STAR-2.5.3a/bin/Linux_x86_64_static/STAR
0086f000-0088a000 rw-p 00000000 00:00 0 
01b2d000-12a84000 rw-p 00000000 00:00 0                                  [heap]
2acf0a40f000-2acf0a511000 rw-p 00000000 00:00 0 
2ad6a4870000-2ad6c4b49000 rw-p 00000000 00:00 0 
2ad6c4b49000-2ad6c4b4a000 ---p 00000000 00:00 0 
2ad6c4b4a000-2ad6c4d4a000 rw-p 00000000 00:00 0                          [stack:181146]
2ad6c4d4a000-2ad6c4d4b000 ---p 00000000 00:00 0 
2ad6c4d4b000-2ad6c4f4b000 rw-p 00000000 00:00 0                          [stack:181145]
2ad6c4f4b000-2ad6c4f4c000 ---p 00000000 00:00 0 
2ad6c4f4c000-2ad6c53fc000 rw-p 00000000 00:00 0                          [stack:181144]
2ad6c5510000-2ad6c5911000 rw-p 00000000 00:00 0 
2ad6c5916000-2ad6c7a2f000 rw-p 00000000 00:00 0 
2ad6c7a2f000-2ad6c7a30000 ---p 00000000 00:00 0 
2ad6c7a30000-2ad6c7c30000 rw-p 00000000 00:00 0 
2ad6c7c30000-2ad6c7c31000 ---p 00000000 00:00 0 
2ad6c7c31000-2ad6c7e31000 rw-p 00000000 00:00 0 
2ad6c8000000-2ad6c85ab000 rw-p 00000000 00:00 0 
2ad6c85ab000-2ad6cc000000 ---p 00000000 00:00 0 
2ad6cc000000-2ad6cc5c4000 rw-p 00000000 00:00 0 
2ad6cc5c4000-2ad6d0000000 ---p 00000000 00:00 0 
2ad6d0000000-2ad6d03e7000 rw-p 00000000 00:00 0 
2ad6d03e7000-2ad6d4000000 ---p 00000000 00:00 0 
2ad6d4000000-2ad708f03000 rw-p 00000000 00:00 0 
2ad708f03000-2ad708f04000 ---p 00000000 00:00 0 
2ad708f04000-2ad709104000 rw-p 00000000 00:00 0 
7fffaafd9000-7fffab00d000 rw-p 00000000 00:00 0                          [stack]
7fffab1f7000-7fffab1f9000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```

**Comment by alexdobin** [comment]
Hi Philip,

I think something goes wrong with the formatting of the FASTQ files, it seems that STAR only sees ~50 reads. Please try to (i) map without sorting, check how many reads were mapped; (ii) unzip the files before mapping.

Cheers
Alex

**Comment by paulmenzel** [comment]
@plijnzaad, how many threads do you use? It might be related to https://github.com/alexdobin/STAR/issues/512.
